urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

from . import views

app_name = 'datacatalog'
urlpatterns = [ 
    # index showing top items and search bar:
    path('', views.IndexView.as_view(), name='index'),
    path('project', views.IndexProjectByUserView.as_view(), name='projects-byuser'),
    path('datasets', views.IndexDatasetView.as_view(), name='datasets'),
    path('duas', views.IndexDUAView.as_view(), name='duas'),
    path('access', views.IndexDataAccessView.as_view(), name='access'),
    path('keywords', views.IndexKeywordView.as_view(), name='keywords'),
    path('providers', views.IndexDataProviderView.as_view(), name='providers'),
    path('retention', views.IndexRetentionRequestView.as_view(), name='retention'),
    path('retention/active', views.IndexActiveRetentionRequestView.as_view(), name='retention-active'),

    # autocomplete functions:
    path('autocomplete-dataset', 
         views.DatasetAutocomplete.as_view(),
         name='autocomplete-dataset',
         ),
    path('autocomplete-publisher', 
         views.PublisherAutocomplete.as_view(),
         name='autocomplete-publisher',
         ),
    path('autocomplete-project-byuser',
         views.ProjectByUserAutocomplete.as_view(),
         name='autocomplete-project-byuser',
         ),
    path('autocomplete-access', 
         views.AccessAutocomplete.as_view(),
         name='autocomplete-access',
         ),
    path('autocomplete-access-byproject',
         views.AccessByProjectAutocomplete.as_view(),
         name='autocomplete-access-byproject',
         ),
    path('autocomplete-dua', 
         views.DUAAutocomplete.as_view(),
         name='autocomplete-dua',
         ),
    path('autocomplete-keyword', 
         views.KeywordAutocomplete.as_view(),
         name='autocomplete-keyword',
         ),
    path('autocomplete-datafield', 
         views.DataFieldAutocomplete.as_view(),
         name='autocomplete-datafield',
         ),
    path('autocomplete-mediatype', 
         views.MediaSubTypeAutocomplete.as_view(),
         name='autocomplete-mediatype',
         ),
    path('autocomplete-cil', 
         views.CILAutocomplete.as_view(),
         name='autocomplete-cil',
         ),

    # detail views
    path('project/<int:pk>', views.ProjectDetailView.as_view(), name='project-view'),
    path('datasets/<int:pk>', views.DatasetDetailView.as_view(), name='dataset-view'),
    path('ddictionary/<int:pk>', views.datadict_view, name='ddict-file'),
    path('access/<int:pk>', views.DataAccessDetailView.as_view(), name='access-view'),
    path('providers/<int:pk>', views.DataProviderDetailView.as_view(),
         name='provider-view'
         ),
    path('duas/<int:pk>', views.DataUseAgreementDetailView.as_view(), name='dua-view'),
    path('duas/<int:pk>/doc', views.duadoc_view, name='dua-doc-view'),
    path('keywords/<int:pk>', views.KeywordDetailView.as_view(), name='keyword-view'),
    path('datafield/<int:pk>', 
         views.DataFieldDetailView.as_view(),
         name='datafield-view'
         ),
    path('retention/<int:pk>', views.RetentionDetailView.as_view(), name='retention-view'),
    path('retention/methods/<int:pk>', views.methodfile_view, name='methodfile-view'),
    path('retention/inventory/<int:pk>', views.inventoryfile_view, name='inventory-view'),

    # create views
    path('project/add', views.ProjectCreateView.as_view(), name='project-add'),
    path('datasets/add', views.DatasetCreateView.as_view(), name='dataset-add'),
    path('access/add', views.DataAccessCreateView.as_view(), name='access-add'),
    path('providers/add', views.DataProviderCreateView.as_view(), name='provider-add'),
    path('duas/add', views.DataUseAgreementCreateView.as_view(), name='dua-add'),
    path('keywords/add', views.KeywordCreateView.as_view(), name='keyword-add'),
    path('datafield/add', views.DataFieldCreateView.as_view(), name='datafield-add'),
    path('retention/add', views.RetentionRequestCreateView.as_view(), name='retention-add'),

    # update views
    path('project/update/<int:pk>', views.ProjectUpdateView.as_view(),
         name='project-update'
         ),
    path('datasets/update/<int:pk>', views.DatasetUpdateView.as_view(),
         name='dataset-update'
         ),
    path('access/update/<int:pk>', views.DataAccessUpdateView.as_view(), 
         name='access-update'
         ),
    path('providers/update/<int:pk>', views.DataProviderUpdateView.as_view(), 
         name='provider-update'
         ),
    path('duas/update/<int:pk>', views.DataUseAgreementUpdateView.as_view(), 
         name='dua-update'
         ),
    path('keywords/update/<int:pk>', views.KeywordUpdateView.as_view(), 
         name='keyword-update'
         ),
    path('retention/update/<int:pk>', views.RetentionUpdateView.as_view(),
         name='retention-update'
         ),

    # data retention workflow views:
    path('wizard/milestone', views.RetentionWorkflowMilestoneView.as_view(), name='wizard-milestone'),
    path('wizard/<int:pk>/project', views.RetentionWorkflowProjectView.as_view(), name='wizard-project'),
    path('wizard/<int:pk>/data', views.RetentionWorkflowDataView.as_view(), name='wizard-data'),
    path('wizard/<int:pk>/summary', views.RetentionWorkflowSummaryView.as_view(), name='wizard-summary'),

                  # search view:
    path('search/all', views.FullSearch.as_view(), name="full-search"),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models.py
import datetime
from datetime import date

from django.db import models

from django.urls import reverse

from django.contrib.auth.models import User

from persons.models import Person, Department, Organization, Role 


def dictionary_directory_path(instance, filename):
    """
    This function specifies the filepath to save uploaded files to.
    """
    # file will be uploaded to MEDIA_ROOT/dataset<id>/<filename>
    return 'dset{0}/{1}'.format(instance.pk, filename)


def project_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/pi<id>/gov_type/<filename>
    return 'duas/{0}/{1}/{2}'.format(instance.pi, instance.governance_type.name, filename)

def multifile_directory_path(instance, filename):
    """
    This function specifies the filepath to save uploaded files for archiving.
    """
    # file will be uploaded to MEDIA_ROOT/to_archive/<pk>/<filename>
    return f'to_archive/DA{instance.pk}/{filename}'

def method_directory_path(instance, filename):
    """
    This function specifies the filepath to save uploaded data retention method files to.
    """
    # file will be uploaded to MEDIA_ROOT/methods/RR<pk>/<filename>
    return f'methods/RR{instance.pk}/{filename}'

def inventory_directory_path(instance, filename):
    """
    This function specifies the filepath to save uploaded inventory of archived files to.
    """
    # file will be uploaded to MEDIA_ROOT/inventory/RR<pk>/<filename>
    return f'inventory/RR{instance.pk}/{filename}'


class Keyword(models.Model):
    """
    A collection of keywords or tags for mapping to other models (primarily Dataset)
    """
    # date the record was created
    record_creation = models.DateField(auto_now_add=True)
    
    # date the record was most recently modified
    record_update = models.DateField(auto_now=True)
    
    # the user who was signed in at time of record modification
    record_author = models.ForeignKey(User, on_delete=models.CASCADE)
 
    # keyword
    keyword = models.CharField(max_length=64)
    
    # definition / elaboration of keyword
    definition = models.TextField()

    # this is set to true after being checked by the Data Catalog curation team
    curated = models.BooleanField(null=True, blank=True)

    # field to designate whether data should be published
    published = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return "{}".format(self.keyword,)

    def get_absolute_url(self):
        return reverse('datacatalog:keyword-view', kwargs={'pk': self.pk})


class MediaSubType(models.Model):
    """
    This model holds values from www.iana.org media types (formally MIME types).
    """
    # description of the subtype
    name = models.CharField(max_length=256, 
                            unique=True,
                            )
    
    # template indicates the type/subtype id
    template = models.CharField(max_length=256, 
                                unique=True,
                                null=True,
                                blank=True,
                                )
    
    # iana reference
    reference = models.CharField(max_length=256, 
                                 null=True,
                                 blank=True,
                                 )
    
    # indicates now obsolete models
    obsolete = models.BinaryField(null=True, blank=True)
    
    def __str__(self):
        if self.template:
            n = self.template
        else:
            n = self.name
        return "{}".format(n)


class DataField(models.Model):
    # date the record was created
    record_creation = models.DateField(auto_now_add=True)
    
    # date the record was most recently modified
    record_update = models.DateField(auto_now=True)
    
    # the user who was signed in at time of record modification
    record_author = models.ForeignKey(User, on_delete=models.PROTECT)
    
    # field name
    name = models.CharField(max_length=256, 
                            help_text="The name of the field as it appears in schema",
                            )
    
    # field description
    description = models.CharField(max_length=256, 
                                   help_text="Description of the field",
                                   )
    
    # descriptions defining scope of data
    scope = models.CharField(max_length=256, 
                             null=True,
                             blank=True,
                             help_text="""
                                       Descriptions of the scope of the data (eg. min, max, number of records, number
                                       of null values, number of unique values)
                                       """,
                             )
    
    def __str__(self):
        if self.scope:
            s = "{}...".format(self.scope[:20])
        else:
            s = "---"
        return "{} ({}...); {}".format(self.name,
                                       self.description[:20],
                                       s,
                                       )

    def get_absolute_url(self):
        return reverse('datacatalog:datafield-view', kwargs={'pk': self.pk})


class ConfidentialityImpact(models.Model):
    """
    A number of different standards define a confidentiality impact level, which can 
    mutually apply to any given dataset. This model will capture the standards and their 
    levels and definitions, allowing users to apply whatever relevant classification to 
    the dataset as needed.
    """
    # date the record was created
    record_creation = models.DateField(auto_now_add=True)
    
    # date the record was most recently modified
    record_update = models.DateField(auto_now=True)
    
    # the user who was signed in at time of record modification
    record_author = models.ForeignKey(User, on_delete=models.PROTECT)

    # the confidentiality impact level
    impact_level = models.CharField("Impact Level",
                                    max_length=32,
                                    unique=False,
                                    null=False,
                                    blank=False,
                                    help_text="Level as defined by the standard",
                                    )
    
    # for ranking the different scales, we include a separate rank field.
    # 1 is the highest risk level
    impact_rank = models.IntegerField(unique=False,
                                      null=False,
                                      blank=False,
                                      help_text="Rank of impact: 1 is highest risk",
                                      )
    
    # standard
    standard = models.CharField("Standard", 
                                max_length=32, 
                                unique=False, 
                                null=False, 
                                blank=False,
                                help_text="Standard defining the impact level",
                                )
    
    # definition
    definition = models.TextField(null=False, blank=False,)
    
    # url link to the relevant documentation 
    link = models.URLField(max_length=200,)

    def __str__(self):
        return "{}: {}".format(self.standard, self.impact_level)

    def get_absolute_url(self):
        return reverse('datacatalog:cil-view', kwargs={'pk': self.pk})
    

class DataProvider(models.Model):
    """
    This class defines data providers.
    """
    # date the record was created
    record_creation = models.DateField(auto_now_add=True)
    
    # date the record was most recently modified
    record_update = models.DateField(auto_now=True)
    
    # the user who was signed in at time of record modification
    record_author = models.ForeignKey(User, on_delete=models.CASCADE)
 
    # provider organization name
    name = models.CharField(max_length=256)
    
    # provider department
    dept = models.CharField(max_length=128, null=True, blank=True)
    
    # contact phone number
    phone = models.CharField(max_length=32, null=True, blank=True)
    
    # contact email 
    email = models.EmailField(null=True, blank=True)
    
    # provider country of origin
    country = models.CharField(max_length=64, null=True, blank=True)
    
    # provider affiliation: Academic, Hospital, Government, or Private
    ACADEMIC = 'AC'
    MEDICAL = 'ME'
    GOVERNMENT = 'GV'
    PRIVATE = 'PR'
    AFFILIATION_CHOICES = (
            (ACADEMIC, "Academic"),
            (MEDICAL, "Medical provider / Hospital"),
            (GOVERNMENT, "Government"),
            (PRIVATE, "Private institution"),
    )
    affiliation = models.CharField(
                        max_length=2,
                        choices=AFFILIATION_CHOICES,
                        default=GOVERNMENT,
    )

    # this is set to true after being checked by the Data Catalog curation team
    curated = models.BooleanField(null=True, blank=True)

    # field to designate whether data should be published
    published = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return "{}".format(self.name,)

    def get_absolute_url(self):
        return reverse('datacatalog:provider-view', kwargs={'pk': self.pk})


class StorageType(models.Model):
    """
    This class defines the basic storage types and locations in which a set of digital
    objects might be found. This will allow the catalog to display the detailed location
    information for each type in a meaningful way, and ensure objects are only described
    from a single storage source. Creation of new storage types is not intended for end
    users, but only for administrators.
    """
    # date the record was created
    record_creation = models.DateField(auto_now_add=True)

    # date the record was most recently modified
    record_update = models.DateField(auto_now=True)

templates/datacatalog/base-catalog.html
{% extends "base.html" %}
{% load project_tags %}

{% block navblock %}
<style>
.navbar-custom {
    background-color: #CF4520;
}
/* Link */
.navbar-custom .navbar-nav > li > a {
    color: #ffffff;
}
.navbar-custom .navbar-nav > li > a:hover,
.navbar-custom .navbar-nav > li > a:focus {
    color: #ffffff;
    background-color: #E87722;
}

body { padding-top: 55px; }
</style>

<nav class="navbar navbar-expand-md navbar-custom fixed-top">
    <a class="navbar-brand" href="/">{{ APPTITLE }}</a>
    <button class="navbar-toggler"  data-toggle="collapse" 
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            
            {# ## ### CATALOG HOME PAGE ### ## #}
            <li class="nav-item active">
              <a class="nav-link btn-outline-light"
                 href="{% url 'datacatalog:index' %}">Data Catalog (Beta)</a>
            </li>
            
            {# ## ### DROPDOWN ITEM INDEX PAGE LINKS ### ## #}
            <li class="nav-item dropdown">
                <a  class="nav-link dropdown-toggle btn-outline-dark" 
                    href="#" id="DCDropdown" 
                    role="button" data-toggle="dropdown" 
                    aria-haspopup="true" aria-expanded="false">
                    View Details
                </a>
            <div class="dropdown-menu" aria-labelledby="DCDropdown">
                <a class="dropdown-item" href="{% url 'datacatalog:projects-byuser' %}">
                    MY PROJECTS</a>
                <a class="dropdown-item" href="{% url 'datacatalog:datasets' %}">
                    Dataset catalog</a>
                {% if request.user|has_group:"dua_viewing_privileges" %}
                <a class="dropdown-item" href="{% url 'datacatalog:duas' %}">
                    DUAs</a>
                <a class="dropdown-item" href="{% url 'datacatalog:access' %}">
                    Data access</a>
                <a class="dropdown-item" href="{% url 'datacatalog:retention-active' %}">
                    Retention requests</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'datacatalog:providers' %}">
                    Providers</a>
                <a class="dropdown-item" href="{% url 'datacatalog:keywords' %}">
                    Keywords</a>
            </div>        
            </li>
        </ul>
        
        <ul class="navbar-nav mp-auto">    
            {# ## ### PROJECT TITLE ### ## #}
            <li>
              <a class="nav-link mx-auto" href="#" style="fontweight:bold;color:white">
                {% block pagetitle %}{% endblock %}</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">    
            {# ## ### USER ADMIN OPTIONS ### ## #}
            <li class="nav-item dropdown ml-auto">
                <a  class="nav-link dropdown-toggle btn-outline-dark" 
                    href="#" id="AdminDropdown" 
                    role="button" data-toggle="dropdown" 
                    aria-haspopup="true" aria-expanded="false">
                    {{ user.get_username }} <b class="caret"></b>
                </a>
            <div class="dropdown-menu" aria-labelledby="AdminDropdown">
              <a class="dropdown-item text-danger" href="{% url 'datacatalog:projects-byuser' %}">
                    View my projects</a>
              <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">
                Admin page</a>
              <a class="dropdown-item" href="{% url 'frontpage' %}">
                Data Core homepage</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/logout">Logout </a>
            </div>        
            </li>
            
            {# ## ### USER ACTIONS ### ## #}
            <li class="nav-item dropdown">
                <a  class="nav-link dropdown-toggle btn-outline-dark" 
                    href="#" id="ActionsDropdown" 
                    role="button" data-toggle="dropdown" 
                    aria-haspopup="true" aria-expanded="false">
                    Submit New: <b class="caret"></b>
                </a>
            <div class="dropdown-menu" aria-labelledby="ActionsDropdown">
                <a class="dropdown-item text-danger" href="{% url 'datacatalog:retention-add' %}">
                    Data retention request</a>
                <a class="dropdown-item text-danger"
                   href="{% url 'datacatalog:wizard-milestone' %}" >
                   Data retention wizard</a>
                <a class="dropdown-item" href="{% url 'datacatalog:project-add' %}">
                    Project</a>
                <a class="dropdown-item" href="{% url 'datacatalog:access-add' %}">
                    Data location</a>
                <a class="dropdown-item" href="{% url 'datacatalog:dataset-add' %}">
                    Dataset metadata</a>
                <a class="dropdown-item" href="{% url 'datacatalog:dua-add' %}">
                    Data use agreement</a>
                <a class="dropdown-item" href="{% url 'datacatalog:provider-add' %}">
                    Data provider</a>
                <a class="dropdown-item" href="{% url 'datacatalog:keyword-add' %}">
                    Keyword</a>

            </div>        
            </li>
          
            {# ## ### SEARCH BAR ### ## #}
            <form class="form-inline my-2 my-lg-0" 
                action="{% url 'datacatalog:full-search' %}" 
                method="post">{% csrf_token %}
              
              <div class="input-group">
              <input class="form-control" type="search" 
                placeholder="Search catalog" aria-label="Search"
                name="srch_term" id="srch_term">
              
                <button class="button btn btn-secondary" type="submit">
                    Submit <i class="glyphicon glyphicon-search">
                    </i></button>
              </div>
            </form>            
        
        </ul> 
        {% else %}
            <li><a style="color:white;" 
               href="/accounts/login">Login</a></li>
        {% endif %}  
    </div>
</nav>


{% endblock %}

templates/datacatalog/carddeck_projects.html
    <div class="card-columns">

    {% for project in project_list %}
    {### CARD FOR PROJECT DETAILS ###}
    <div class="card border-dark my-2 shadow">
        <div class="card-header">
            <h5 class="mb-2 text-muted">
                <a href="{% url 'datacatalog:project-view' project.pk %}">{{ project.name }}</a>
            </h5>
        </div>
        <div class="card-body">


            <p> {{ project.description|linebreaks }}</p>
        </div> {# card body #}
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><em>Dataset locations:</em></li>
          {% for da in project.dataaccess_set.all %}
            <li class="list-group-item"><a href="{% url 'datacatalog:access-view' da.pk %}">{{ da.storage_type.name }}</a></li>
          {% endfor %}
            <li class="list-group-item">
                <a
                    class="btn btn-primary"
                    href="{% url 'datacatalog:access-add' %}">Add new data location</a></li>
        </ul>
    </div> {# card #}
    {% endfor %}

  </div> {# column div #}

templates/datacatalog/detail_retention.html
{% extends 'datacatalog/base-catalog.html' %}

{# Load the tag library #}
{% load bootstrap4 %}
{% load project_tags %}
{% load crispy_forms_tags %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}

<style>
/* styling of the tabs*/
#exTab1 .tab-content {
  color : black;
  padding : 5px 15px;
}

#exTab1 .nav-tabs > li > a {
  border-radius: 4px 4px 0 0;
}
</style>

{### Project Header ###}
{% if accessdenied %}
    <h1>You do not have permission to view this request. If you require access, please contact
        <a href="emailto:dcore-ticket@med.cornell.edu"
           target="_blank">dcore-ticket@med.cornell.edu</a> </h1>
{% endif %}

<h2>
    Retention Request: {{ retentionrequest.name }}
</h2>


    {% if retentionrequest.verified %}
        <h2><span class="badge badge-success">Request has been verified</span></h2>
    {% endif %}

    <h3>Milestone: {{ retentionrequest.get_milestone_display }}
        <span class="badge badge-secondary" style="float:right">RR{{ retentionrequest.pk }}</span>
    </h3>
    <h3><small class="text-muted">
                {{ retentionrequest.milestone_pointer }} ({{ retentionrequest.milestone_date }})
        </small>
    </h3>

<h2>
    {% if retentionrequest.locked is not True %}
        {% if request.user|has_group:"datacatalog_editor" or request.user.username == retentionpi.cwid or request.user.username == retentionadmin.cwid or request.user == retentionrequest.record_author %}
        <span>
            <a
               class="btn btn-primary"
               href="{% url 'datacatalog:retention-update' retentionrequest.pk %}">
               Update retention request details
            </a>
        </span>
        {% endif %}
    {% else %}
        <span class="badge badge-danger">Request is now locked</span>
    {% endif %}
    <a  class="btn btn-info" href="{% url 'datacatalog:methodfile-view' retentionrequest.pk %}"
        target="_blank">View methods file
    </a>
    {% if retentionrequest.inventory %}
    <a  class="btn btn-info" href="{% url 'datacatalog:inventory-view' retentionrequest.pk %}"
        target="_blank">View inventory
    </a>
    {% endif %}
</h2>

<table class="table table-striped table-hover table-sm">
    <tr><td>Project</td>
        <td>{% if retentionrequest.project %}
                <a href="{% url 'datacatalog:project-view' retentionrequest.project.pk %}">
                    {{ retentionrequest.project }}</a>
            {% else %}
                No project specified.
            {% endif %}
        </td></tr>
    <tr><td>PI</td><td>{{ retentionpi }}</td></tr>
    <tr><td>Co-PI(s)</td><td>{% for pi in retentionrequest.project.other_pis.all %}{{ pi }};{% endfor %} </td></tr>
    <tr><td>Other editor(s)</td><td>{% for ed in retentionrequest.project.other_editors.all %}{{ ed }}; {% endfor %}</td>
    <tr><td>Retention requested by</td><td>{{ retentionrequest.record_author.first_name }}
                                            {{ retentionrequest.record_author.last_name }}
                                            ({{ retentionrequest.record_author.username }})</td></tr>
    <tr><td>Request created</td><td>{{ retentionrequest.record_creation }}</td></tr>
    <tr><td>Last update</td><td>{{ retentionrequest.record_update }}</td></tr>
    {% if retentionrequest.ticket %}
        <tr><td>ServiceNow Ticket</td><td>{{ retentionrequest.ticket }}</td></tr>
    {% endif %}
    <tr><td>Comments</td><td>{{ retentionrequest.comments }}</td></tr>
</table>

{### Tiles of all storage items  ###}
<div class="card-columns">
    {% for da in retentionrequest.to_archive.all %}
        {% include "datacatalog/card_dataaccess.html" %}
    {% endfor %}
</div>

    {% if request.user|has_group:"datacatalog_editor" %}
    <div class="row">
        <a
           class="btn btn-primary mr-1"
           href="{% url 'datacatalog:retention-update' retentionrequest.pk %}">
           Update retention request details
        </a>

        <form action="" method="post">
          {% csrf_token %}
          <input name="marklocked" type="submit" class="btn btn-info mr-1" value="Lock submission" />
        </form>

        <form action="" method="post">
          {% csrf_token %}
          <input name="markunlocked" type="submit" class="btn btn-warning mr-1" value="Unlock submission" />
        </form>

        <form action="" method="post">
          {% csrf_token %}
          <input name="markarchived" type="submit" class="btn btn-danger mr-1" value="Mark data as archived" />
        </form>

        <form action="" method="post">
          {% csrf_token %}
          <input name="markverified" type="submit" class="btn btn-success mr-1" value="Mark as verified" />
        </form>

    </div>
        <br/><br/>

    <div class="card shadow">
        <div class="card-header bg-light">
            <h3>Upload inventory list after archiving</h3>
        </div>
        <div class="card-body">

            {{ form_inventory.media }}

            <form enctype="multipart/form-data"  action="" method="post">
                {% csrf_token %}
                {% crispy form_inventory %}
            </form>
        </div>
    </div>

    {% endif %}

{% endblock %}

templates/datacatalog/index_datasets.html
{% extends 'datacatalog/base-catalog.html' %}

{% block content %}
<h1>
All {{ dataset_list|length }} Datasets:
</h1>

{% include 'datacatalog/table_datasets.html' %}

<a  class="btn btn-primary" href="{% url 'datacatalog:dataset-add' %}">Add new dataset</a>

{% endblock content %}

templates/datacatalog/index_projects.html
{% extends 'datacatalog/base-catalog.html' %}

{# Load the tag library #}
{% load bootstrap4 %}
{% load project_tags %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}

<style>
/* styling of the tabs*/
#exTab1 .tab-content {
  color : black;
  padding : 5px 15px;
}

#exTab1 .nav-tabs > li > a {
  border-radius: 4px 4px 0 0;
}
</style>



<h1>
    {{ project_list|length  }} project{{ project_list|length|pluralize:",s" }} for {{ request.user.first_name }} {{ request.user.last_name }}
</h1>
<h2>
        <a 
           class="btn btn-primary"
           href="{% url 'datacatalog:project-add' %}">Create new project</a>
        <a 
           class="btn btn-primary"
           href="{% url 'datacatalog:access-add' %}">Add new data location</a>
        <a 
           class="btn btn-danger"
           href="{% url 'datacatalog:retention-add' %}">Request data retention</a>
        <a
           class="btn btn-danger"
           href="{% url 'datacatalog:wizard-milestone' %}">Retention request wizard</a>
</h2>

<div class="container">
    {% if mypiprojects|length %}
        <div class="alert alert-info" role="alert">My projects</div>
        {% with mypiprojects as project_list %}
            {% include 'datacatalog/carddeck_projects.html' %}
        {% endwith %}
    {% endif %}

    {% if myotherpisprojects|length %}
        <div class="alert alert-info" role="alert">Projects as co-PI</div>
        {% with myotherpisprojects as project_list %}
            {% include 'datacatalog/carddeck_projects.html' %}
        {% endwith %}
    {% endif %}

    {% if myothereditorsprojects|length %}
        <div class="alert alert-info" role="alert">other projects with editing rights</div>
        {% with myothereditorsprojects as project_list %}
            {% include 'datacatalog/carddeck_projects.html' %}
        {% endwith %}
    {% endif %}

</div> {# container div #}

    <p></p>
    <p></p>
    <h4>Dataset retention requests</h4>
        {% include 'datacatalog/table_retention_requests.html' %}
{% endblock %}

templates/datacatalog/table_datasets.html
<table class="table table-striped table-hover" id="DatasetTable">
<thead class="thead-default">
    <tr>
        <th>Title</th>
        <th>Provider</th>
        <th>Period </th>
        <th>Keywords</th>
    </tr>
</thead>

{% for ds in dataset_list %}
{% if ds.published %}
    <tr>
    <td><a href="{% url 'datacatalog:dataset-view' ds.pk %}">{{ ds.title }}</a></td>
    <td>{{ ds.publisher }}</td>
    <td> {{ ds.period_start }} - {{ ds.period_end }}</td>
    <td> {% for kw in ds.keywords.all %}
            <span class="badge progress-bar-info">
            <a  href="{% url 'datacatalog:keyword-view' kw.pk %}">
                <span class="badge badge-info">{{ kw.keyword }}</span>
            </a></span>{% endfor %}</td>
    </tr>
{% endif %}
{% endfor %}
</table>